using MedyxHMS.Data;
using MedyxHMS.Models;
using Microsoft.EntityFrameworkCore;

namespace MedyxHMS.Services.Implementations
{
    /// <summary>
    /// Seeds realistic demo/dummy data for development and testing.
    /// All operations are idempotent — they skip if data already exists.
    /// </summary>
    public class DemoDataSeeder
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<DemoDataSeeder> _logger;

        public DemoDataSeeder(ApplicationDbContext context, ILogger<DemoDataSeeder> logger)
        {
            _context = context;
            _logger = logger;
        }

        public async Task SeedAsync()
        {
            _logger.LogInformation("Starting demo data seeding...");

            await PatchSchemaAsync();
            await SeedDepartmentsAsync();
            await SeedDoctorsAsync();
            await SeedWardsAndBedsAsync();
            await SeedMedicinesAsync();
            await SeedPatientsAsync();
            await SeedAppointmentsAsync();
            await SeedOpdVisitsAsync();
            await SeedIpdAdmissionsAsync();
            await SeedBillsAsync();

            _logger.LogInformation("Demo data seeding complete.");
        }

        // ── Schema patches ───────────────────────────────────────────────────────

        private async Task PatchSchemaAsync()
        {
            // Drop the spurious FK from Appointments.StaffId -> Staff.Id.
            // This FK was auto-generated by EF Core convention but is incorrect;
            // StaffId is a computed shim that mirrors DoctorId.
            await _context.Database.ExecuteSqlRawAsync(@"
IF EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'FK_Appointments_Staff_StaffId'
      AND parent_object_id = OBJECT_ID(N'[dbo].[Appointments]')
)
BEGIN
    ALTER TABLE [dbo].[Appointments] DROP CONSTRAINT [FK_Appointments_Staff_StaffId];
END");
        }

        // ── Departments ──────────────────────────────────────────────────────────

        private async Task SeedDepartmentsAsync()
        {
            if (await _context.Departments.AnyAsync()) return;

            var departments = new[]
            {
                new Department { Name = "General Medicine",    Description = "Primary care and general internal medicine", HeadOfDepartment = "Dr. Ahmad Khan",     IsActive = true, CreatedDate = DateTime.UtcNow },
                new Department { Name = "Cardiology",          Description = "Heart and cardiovascular disorders",          HeadOfDepartment = "Dr. Sarah Williams",  IsActive = true, CreatedDate = DateTime.UtcNow },
                new Department { Name = "Orthopedics",         Description = "Bone and joint disorders",                   HeadOfDepartment = "Dr. Rahul Mehta",     IsActive = true, CreatedDate = DateTime.UtcNow },
                new Department { Name = "Pediatrics",          Description = "Medical care for children",                  HeadOfDepartment = "Dr. Priya Sharma",    IsActive = true, CreatedDate = DateTime.UtcNow },
                new Department { Name = "Gynecology",          Description = "Women's reproductive health",                HeadOfDepartment = "Dr. Amina Hassan",    IsActive = true, CreatedDate = DateTime.UtcNow },
                new Department { Name = "ENT",                 Description = "Ear, nose and throat conditions",            HeadOfDepartment = "Dr. James Okafor",    IsActive = true, CreatedDate = DateTime.UtcNow },
                new Department { Name = "Radiology",           Description = "Diagnostic imaging services",                HeadOfDepartment = "Dr. Fatima Al-Rashid",IsActive = true, CreatedDate = DateTime.UtcNow },
                new Department { Name = "Pathology",           Description = "Laboratory diagnostics and tests",           HeadOfDepartment = "Dr. Li Wei",          IsActive = true, CreatedDate = DateTime.UtcNow },
                new Department { Name = "Emergency",           Description = "Emergency and trauma care",                  HeadOfDepartment = "Dr. Carlos Reyes",    IsActive = true, CreatedDate = DateTime.UtcNow },
                new Department { Name = "Surgery",             Description = "Surgical procedures and operations",         HeadOfDepartment = "Dr. Nakamura Kenji",  IsActive = true, CreatedDate = DateTime.UtcNow },
            };

            await _context.Departments.AddRangeAsync(departments);
            await _context.SaveChangesAsync();
            _logger.LogInformation("Seeded {Count} departments", departments.Length);
        }

        // ── Doctors ──────────────────────────────────────────────────────────────

        private async Task SeedDoctorsAsync()
        {
            if (await _context.Doctors.AnyAsync()) return;

            var depts = await _context.Departments.ToDictionaryAsync(d => d.Name, d => d.Id);

            var doctors = new[]
            {
                new Doctor { EmployeeId="DOC-001", FirstName="Ahmad",   LastName="Khan",       Specialization="General Physician",  LicenseNumber="LIC-GM-001", Phone="9100010001", Email="ahmad.khan@medyx.local",     DepartmentId=depts["General Medicine"], IsActive=true, CreatedDate=DateTime.UtcNow },
                new Doctor { EmployeeId="DOC-002", FirstName="Sarah",   LastName="Williams",   Specialization="Cardiologist",        LicenseNumber="LIC-CR-001", Phone="9100010002", Email="sarah.williams@medyx.local",   DepartmentId=depts["Cardiology"],       IsActive=true, CreatedDate=DateTime.UtcNow },
                new Doctor { EmployeeId="DOC-003", FirstName="Rahul",   LastName="Mehta",      Specialization="Orthopedic Surgeon",  LicenseNumber="LIC-OR-001", Phone="9100010003", Email="rahul.mehta@medyx.local",      DepartmentId=depts["Orthopedics"],      IsActive=true, CreatedDate=DateTime.UtcNow },
                new Doctor { EmployeeId="DOC-004", FirstName="Priya",   LastName="Sharma",     Specialization="Pediatrician",        LicenseNumber="LIC-PD-001", Phone="9100010004", Email="priya.sharma@medyx.local",     DepartmentId=depts["Pediatrics"],       IsActive=true, CreatedDate=DateTime.UtcNow },
                new Doctor { EmployeeId="DOC-005", FirstName="Amina",   LastName="Hassan",     Specialization="Gynaecologist",       LicenseNumber="LIC-GY-001", Phone="9100010005", Email="amina.hassan@medyx.local",     DepartmentId=depts["Gynecology"],       IsActive=true, CreatedDate=DateTime.UtcNow },
                new Doctor { EmployeeId="DOC-006", FirstName="James",   LastName="Okafor",     Specialization="ENT Specialist",      LicenseNumber="LIC-EN-001", Phone="9100010006", Email="james.okafor@medyx.local",     DepartmentId=depts["ENT"],              IsActive=true, CreatedDate=DateTime.UtcNow },
                new Doctor { EmployeeId="DOC-007", FirstName="Carlos",  LastName="Reyes",      Specialization="Emergency Physician", LicenseNumber="LIC-EM-001", Phone="9100010007", Email="carlos.reyes@medyx.local",     DepartmentId=depts["Emergency"],        IsActive=true, CreatedDate=DateTime.UtcNow },
                new Doctor { EmployeeId="DOC-008", FirstName="Nakamura",LastName="Kenji",      Specialization="General Surgeon",     LicenseNumber="LIC-SG-001", Phone="9100010008", Email="nakamura.kenji@medyx.local",   DepartmentId=depts["Surgery"],          IsActive=true, CreatedDate=DateTime.UtcNow },
            };

            await _context.Doctors.AddRangeAsync(doctors);
            await _context.SaveChangesAsync();
            _logger.LogInformation("Seeded {Count} doctors", doctors.Length);
        }

        // ── Wards & Beds ─────────────────────────────────────────────────────────

        private async Task SeedWardsAndBedsAsync()
        {
            if (await _context.Wards.AnyAsync()) return;

            var wards = new[]
            {
                new Ward { Name = "General Ward A",  Description = "Standard general admission ward",    TotalBeds = 20, OccupiedBeds = 0, IsActive = true, CreatedDate = DateTime.UtcNow },
                new Ward { Name = "ICU",             Description = "Intensive care unit",                TotalBeds = 8,  OccupiedBeds = 0, IsActive = true, CreatedDate = DateTime.UtcNow },
                new Ward { Name = "Private Ward",    Description = "Private single-patient rooms",       TotalBeds = 10, OccupiedBeds = 0, IsActive = true, CreatedDate = DateTime.UtcNow },
                new Ward { Name = "Pediatric Ward",  Description = "Ward dedicated to paediatric care",  TotalBeds = 12, OccupiedBeds = 0, IsActive = true, CreatedDate = DateTime.UtcNow },
            };

            await _context.Wards.AddRangeAsync(wards);
            await _context.SaveChangesAsync();

            var genWard    = wards[0];
            var icu        = wards[1];
            var privWard   = wards[2];
            var pedWard    = wards[3];

            var beds = new List<Bed>();

            // General Ward — 10 beds
            for (var i = 1; i <= 10; i++)
                beds.Add(new Bed { WardId = genWard.Id, BedNumber = $"GA-{i:D2}", Block = "A", Floor = "1", RoomNumber = $"1{i:D2}", BedType = "General",  DailyCharges = 500,  Status = "Available", IsActive = true, CreatedDate = DateTime.UtcNow });

            // ICU — 4 beds
            for (var i = 1; i <= 4; i++)
                beds.Add(new Bed { WardId = icu.Id,     BedNumber = $"ICU-{i:D2}", Block = "B", Floor = "2", RoomNumber = $"2{i:D2}", BedType = "ICU",     DailyCharges = 4000, Status = "Available", IsActive = true, CreatedDate = DateTime.UtcNow });

            // Private Ward — 5 beds
            for (var i = 1; i <= 5; i++)
                beds.Add(new Bed { WardId = privWard.Id,BedNumber = $"PV-{i:D2}", Block = "C", Floor = "3", RoomNumber = $"3{i:D2}", BedType = "Private",  DailyCharges = 2500, Status = "Available", IsActive = true, CreatedDate = DateTime.UtcNow });

            // Paediatric Ward — 5 beds
            for (var i = 1; i <= 5; i++)
                beds.Add(new Bed { WardId = pedWard.Id, BedNumber = $"PD-{i:D2}", Block = "D", Floor = "1", RoomNumber = $"4{i:D2}", BedType = "General",  DailyCharges = 600,  Status = "Available", IsActive = true, CreatedDate = DateTime.UtcNow });

            await _context.Beds.AddRangeAsync(beds);
            await _context.SaveChangesAsync();
            _logger.LogInformation("Seeded {WardCount} wards and {BedCount} beds", wards.Length, beds.Count);
        }

        // ── Medicines ────────────────────────────────────────────────────────────

        private async Task SeedMedicinesAsync()
        {
            if (await _context.Medicines.AnyAsync()) return;

            var expiry = DateTime.UtcNow.AddYears(2);
            var medicines = new[]
            {
                new Medicine { Name="Paracetamol 500mg", GenericName="Paracetamol",   Category="Analgesic",     DosageForm="Tablet",   Strength="500mg",   Manufacturer="Cipla",        UnitPrice=1.5m,   StockQuantity=2000, MinStockLevel=100, ExpiryDate=expiry, BatchNumber="B-2025-001", IsActive=true, CreatedDate=DateTime.UtcNow },
                new Medicine { Name="Amoxicillin 500mg", GenericName="Amoxicillin",   Category="Antibiotic",    DosageForm="Capsule",  Strength="500mg",   Manufacturer="Sun Pharma",   UnitPrice=4.0m,   StockQuantity=800,  MinStockLevel=50,  ExpiryDate=expiry, BatchNumber="B-2025-002", IsActive=true, CreatedDate=DateTime.UtcNow },
                new Medicine { Name="Metformin 500mg",   GenericName="Metformin",     Category="Antidiabetic",  DosageForm="Tablet",   Strength="500mg",   Manufacturer="USV",          UnitPrice=2.5m,   StockQuantity=1200, MinStockLevel=100, ExpiryDate=expiry, BatchNumber="B-2025-003", IsActive=true, CreatedDate=DateTime.UtcNow },
                new Medicine { Name="Atorvastatin 10mg", GenericName="Atorvastatin",  Category="Antilipemic",   DosageForm="Tablet",   Strength="10mg",    Manufacturer="Ranbaxy",      UnitPrice=8.0m,   StockQuantity=600,  MinStockLevel=50,  ExpiryDate=expiry, BatchNumber="B-2025-004", IsActive=true, CreatedDate=DateTime.UtcNow },
                new Medicine { Name="Omeprazole 20mg",   GenericName="Omeprazole",    Category="PPI",           DosageForm="Capsule",  Strength="20mg",    Manufacturer="Zydus",        UnitPrice=3.0m,   StockQuantity=900,  MinStockLevel=50,  ExpiryDate=expiry, BatchNumber="B-2025-005", IsActive=true, CreatedDate=DateTime.UtcNow },
                new Medicine { Name="Amlodipine 5mg",    GenericName="Amlodipine",    Category="Antihypertensive",DosageForm="Tablet", Strength="5mg",     Manufacturer="Lupin",        UnitPrice=3.5m,   StockQuantity=750,  MinStockLevel=50,  ExpiryDate=expiry, BatchNumber="B-2025-006", IsActive=true, CreatedDate=DateTime.UtcNow },
                new Medicine { Name="Ibuprofen 400mg",   GenericName="Ibuprofen",     Category="NSAID",         DosageForm="Tablet",   Strength="400mg",   Manufacturer="Abbott",       UnitPrice=2.0m,   StockQuantity=1500, MinStockLevel=100, ExpiryDate=expiry, BatchNumber="B-2025-007", IsActive=true, CreatedDate=DateTime.UtcNow },
                new Medicine { Name="Azithromycin 250mg",GenericName="Azithromycin",  Category="Antibiotic",    DosageForm="Tablet",   Strength="250mg",   Manufacturer="Cipla",        UnitPrice=12.0m,  StockQuantity=400,  MinStockLevel=30,  ExpiryDate=expiry, BatchNumber="B-2025-008", IsActive=true, CreatedDate=DateTime.UtcNow },
                new Medicine { Name="Insulin Glargine",  GenericName="Insulin Glargine",Category="Insulin",     DosageForm="Injection",Strength="100U/ml", Manufacturer="Novo Nordisk", UnitPrice=450.0m, StockQuantity=100,  MinStockLevel=10,  ExpiryDate=expiry, BatchNumber="B-2025-009", IsActive=true, CreatedDate=DateTime.UtcNow },
                new Medicine { Name="Salbutamol Inhaler",GenericName="Salbutamol",    Category="Bronchodilator",DosageForm="Inhaler",  Strength="100mcg",  Manufacturer="GSK",          UnitPrice=85.0m,  StockQuantity=200,  MinStockLevel=20,  ExpiryDate=expiry, BatchNumber="B-2025-010", IsActive=true, CreatedDate=DateTime.UtcNow },
                new Medicine { Name="Cetirizine 10mg",   GenericName="Cetirizine",    Category="Antihistamine", DosageForm="Tablet",   Strength="10mg",    Manufacturer="Cadila",       UnitPrice=1.8m,   StockQuantity=1000, MinStockLevel=50,  ExpiryDate=expiry, BatchNumber="B-2025-011", IsActive=true, CreatedDate=DateTime.UtcNow },
                new Medicine { Name="Clopidogrel 75mg",  GenericName="Clopidogrel",   Category="Antiplatelet",  DosageForm="Tablet",   Strength="75mg",    Manufacturer="Sanofi",       UnitPrice=9.5m,   StockQuantity=500,  MinStockLevel=30,  ExpiryDate=expiry, BatchNumber="B-2025-012", IsActive=true, CreatedDate=DateTime.UtcNow },
            };

            await _context.Medicines.AddRangeAsync(medicines);
            await _context.SaveChangesAsync();
            _logger.LogInformation("Seeded {Count} medicines", medicines.Length);
        }

        // ── Patients ─────────────────────────────────────────────────────────────

        private async Task SeedPatientsAsync()
        {
            if (await _context.Patients.CountAsync() > 2) return; // skip if real patients already exist

            // Ensure UserId is nullable so demo patients without portal accounts can be inserted
            await _context.Database.ExecuteSqlRawAsync(@"
IF COL_LENGTH(N'[dbo].[Patients]', N'UserId') IS NOT NULL
BEGIN
    IF EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'Patients'
          AND COLUMN_NAME = 'UserId'
          AND IS_NULLABLE = 'NO'
    )
    BEGIN
        -- Drop FK if it exists before altering the column
        DECLARE @fkName NVARCHAR(256);
        SELECT @fkName = fk.name
        FROM sys.foreign_keys fk
        INNER JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
        INNER JOIN sys.columns c ON fkc.parent_object_id = c.object_id AND fkc.parent_column_id = c.column_id
        WHERE fk.parent_object_id = OBJECT_ID(N'[dbo].[Patients]')
          AND c.name = N'UserId';

        IF @fkName IS NOT NULL
        BEGIN
            DECLARE @sql NVARCHAR(500) = N'ALTER TABLE [dbo].[Patients] DROP CONSTRAINT ' + @fkName;
            EXEC sp_executesql @sql;
        END

        ALTER TABLE [dbo].[Patients] ALTER COLUMN [UserId] NVARCHAR(450) NULL;

        -- Re-add FK as nullable-compatible
        IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_Patients_AspNetUsers_UserId')
        BEGIN
            ALTER TABLE [dbo].[Patients]
                ADD CONSTRAINT [FK_Patients_AspNetUsers_UserId]
                FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers]([Id]);
        END
    END
END");

            var patients = new[]
            {
                new Patient { PatientId="P00001", FirstName="Mohamed",  LastName="Al-Farsi",    Email="m.alfarsi@email.com",   Phone="9200001001", DateOfBirth=new DateTime(1985,3,12), Gender="Male",   Address="12 Al-Noor St",   City="Dubai",       State="Dubai",       Country="UAE",   PostalCode="00001", BloodGroup="A+",  EmergencyContactName="Fatima Al-Farsi",   EmergencyContactPhone="9200001002", EmergencyContactRelation="Wife",   MaritalStatus="Married", Occupation="Engineer",   IsActive=true, CreatedDate=DateTime.UtcNow, LastVisitDate=DateTime.UtcNow.AddDays(-5)  },
                new Patient { PatientId="P00002", FirstName="Priya",    LastName="Nair",         Email="priya.nair@email.com",   Phone="9200002001", DateOfBirth=new DateTime(1992,7,24), Gender="Female", Address="45 MG Road",      City="Kochi",       State="Kerala",      Country="India", PostalCode="682001", BloodGroup="B+",  EmergencyContactName="Arun Nair",         EmergencyContactPhone="9200002002", EmergencyContactRelation="Husband",MaritalStatus="Married", Occupation="Teacher",    IsActive=true, CreatedDate=DateTime.UtcNow, LastVisitDate=DateTime.UtcNow.AddDays(-10) },
                new Patient { PatientId="P00003", FirstName="John",     LastName="Mensah",       Email="j.mensah@email.com",     Phone="9200003001", DateOfBirth=new DateTime(1978,11,5), Gender="Male",   Address="78 Accra Ave",    City="Accra",       State="Greater Accra",Country="Ghana",PostalCode="GA001",  BloodGroup="O-",  EmergencyContactName="Martha Mensah",     EmergencyContactPhone="9200003002", EmergencyContactRelation="Sister", MaritalStatus="Widowed", Occupation="Farmer",     IsActive=true, CreatedDate=DateTime.UtcNow, LastVisitDate=DateTime.UtcNow.AddDays(-3)  },
                new Patient { PatientId="P00004", FirstName="Sofia",    LastName="Rodriguez",    Email="sofia.r@email.com",      Phone="9200004001", DateOfBirth=new DateTime(2005,6,18), Gender="Female", Address="23 Calle Luna",   City="Bogota",      State="Cundinamarca",Country="Colombia",PostalCode="11001", BloodGroup="AB+", EmergencyContactName="Luis Rodriguez",    EmergencyContactPhone="9200004002", EmergencyContactRelation="Father", MaritalStatus="Single",  Occupation="Student",    IsActive=true, CreatedDate=DateTime.UtcNow, LastVisitDate=DateTime.UtcNow.AddDays(-7)  },
                new Patient { PatientId="P00005", FirstName="David",    LastName="Osei",         Email="david.osei@email.com",   Phone="9200005001", DateOfBirth=new DateTime(1965,1,30), Gender="Male",   Address="14 Ring Road",    City="Kumasi",      State="Ashanti",     Country="Ghana", PostalCode="GA002",  BloodGroup="A-",  EmergencyContactName="Mary Osei",         EmergencyContactPhone="9200005002", EmergencyContactRelation="Wife",   MaritalStatus="Married", Occupation="Businessman", IsActive=true, CreatedDate=DateTime.UtcNow, LastVisitDate=DateTime.UtcNow.AddDays(-14) },
                new Patient { PatientId="P00006", FirstName="Aisha",    LastName="Usman",        Email="aisha.usman@email.com",  Phone="9200006001", DateOfBirth=new DateTime(1988,9,15), Gender="Female", Address="6 Sultan Road",   City="Lagos",       State="Lagos",       Country="Nigeria",PostalCode="NG001", BloodGroup="B-",  EmergencyContactName="Ibrahim Usman",     EmergencyContactPhone="9200006002", EmergencyContactRelation="Brother",MaritalStatus="Married", Occupation="Nurse",      IsActive=true, CreatedDate=DateTime.UtcNow, LastVisitDate=DateTime.UtcNow.AddDays(-2)  },
                new Patient { PatientId="P00007", FirstName="Wei",      LastName="Zhang",        Email="wei.zhang@email.com",    Phone="9200007001", DateOfBirth=new DateTime(1970,4,22), Gender="Male",   Address="99 Nanjing Rd",   City="Shanghai",    State="Shanghai",    Country="China", PostalCode="200000", BloodGroup="O+",  EmergencyContactName="Li Zhang",          EmergencyContactPhone="9200007002", EmergencyContactRelation="Son",    MaritalStatus="Married", Occupation="Manager",    IsActive=true, CreatedDate=DateTime.UtcNow, LastVisitDate=DateTime.UtcNow.AddDays(-20) },
                new Patient { PatientId="P00008", FirstName="Fatima",   LastName="Al-Rashid",    Email="fatima.ar@email.com",    Phone="9200008001", DateOfBirth=new DateTime(2010,12,3), Gender="Female", Address="31 King Fahd Rd", City="Riyadh",      State="Riyadh",      Country="Saudi Arabia",PostalCode="SA001",BloodGroup="A+", EmergencyContactName="Hassan Al-Rashid",  EmergencyContactPhone="9200008002", EmergencyContactRelation="Father", MaritalStatus="Single",  Occupation="Student",    IsActive=true, CreatedDate=DateTime.UtcNow, LastVisitDate=DateTime.UtcNow.AddDays(-1)  },
                new Patient { PatientId="P00009", FirstName="Carlos",   LastName="Silva",        Email="carlos.silva@email.com", Phone="9200009001", DateOfBirth=new DateTime(1955,8,11), Gender="Male",   Address="77 Av. Paulista", City="Sao Paulo",   State="Sao Paulo",   Country="Brazil",PostalCode="01310",  BloodGroup="AB-", EmergencyContactName="Ana Silva",         EmergencyContactPhone="9200009002", EmergencyContactRelation="Daughter",MaritalStatus="Divorced",Occupation="Retired",   IsActive=true, CreatedDate=DateTime.UtcNow, LastVisitDate=DateTime.UtcNow.AddDays(-6)  },
                new Patient { PatientId="P00010", FirstName="Nkechi",   LastName="Obi",          Email="nkechi.obi@email.com",   Phone="9200010001", DateOfBirth=new DateTime(1998,2,28), Gender="Female", Address="8 Trans-Amadi",   City="Port Harcourt",State="Rivers",     Country="Nigeria",PostalCode="NG002", BloodGroup="B+",  EmergencyContactName="Emeka Obi",         EmergencyContactPhone="9200010002", EmergencyContactRelation="Brother",MaritalStatus="Single",  Occupation="Accountant", IsActive=true, CreatedDate=DateTime.UtcNow, LastVisitDate=DateTime.UtcNow.AddDays(-4)  },
                new Patient { PatientId="P00011", FirstName="Haruto",   LastName="Tanaka",       Email="h.tanaka@email.com",     Phone="9200011001", DateOfBirth=new DateTime(1982,5,7),  Gender="Male",   Address="12 Shibuya",      City="Tokyo",       State="Tokyo",       Country="Japan", PostalCode="150001", BloodGroup="A+",  EmergencyContactName="Yuki Tanaka",       EmergencyContactPhone="9200011002", EmergencyContactRelation="Wife",   MaritalStatus="Married", Occupation="IT Specialist",IsActive=true, CreatedDate=DateTime.UtcNow, LastVisitDate=DateTime.UtcNow.AddDays(-8)  },
                new Patient { PatientId="P00012", FirstName="Grace",    LastName="Otieno",       Email="grace.otieno@email.com", Phone="9200012001", DateOfBirth=new DateTime(1975,10,19),Gender="Female", Address="5 Uhuru Hwy",     City="Nairobi",     State="Nairobi",     Country="Kenya", PostalCode="KE001",  BloodGroup="O+",  EmergencyContactName="Peter Otieno",      EmergencyContactPhone="9200012002", EmergencyContactRelation="Husband",MaritalStatus="Married", Occupation="Lecturer",   IsActive=true, CreatedDate=DateTime.UtcNow, LastVisitDate=DateTime.UtcNow.AddDays(-12) },
                new Patient { PatientId="P00013", FirstName="Omar",     LastName="Khalil",       Email="omar.khalil@email.com",  Phone="9200013001", DateOfBirth=new DateTime(1940,6,3),  Gender="Male",   Address="20 Zamalek St",   City="Cairo",       State="Cairo",       Country="Egypt", PostalCode="EG001",  BloodGroup="B+",  EmergencyContactName="Salma Khalil",      EmergencyContactPhone="9200013002", EmergencyContactRelation="Daughter",MaritalStatus="Widowed", Occupation="Retired",    IsActive=true, CreatedDate=DateTime.UtcNow, LastVisitDate=DateTime.UtcNow.AddDays(-15) },
                new Patient { PatientId="P00014", FirstName="Ananya",   LastName="Gupta",        Email="ananya.gupta@email.com", Phone="9200014001", DateOfBirth=new DateTime(1995,3,14), Gender="Female", Address="88 Lajpat Nagar", City="Delhi",       State="Delhi",       Country="India", PostalCode="110024", BloodGroup="A-",  EmergencyContactName="Vikram Gupta",      EmergencyContactPhone="9200014002", EmergencyContactRelation="Father", MaritalStatus="Single",  Occupation="Software Dev",IsActive=true, CreatedDate=DateTime.UtcNow, LastVisitDate=DateTime.UtcNow.AddDays(-9)  },
                new Patient { PatientId="P00015", FirstName="Emmanuel", LastName="Diallo",       Email="e.diallo@email.com",     Phone="9200015001", DateOfBirth=new DateTime(1960,7,25), Gender="Male",   Address="3 Route Nationale",City="Dakar",      State="Dakar",       Country="Senegal",PostalCode="SN001", BloodGroup="AB+", EmergencyContactName="Mariama Diallo",    EmergencyContactPhone="9200015002", EmergencyContactRelation="Wife",   MaritalStatus="Married", Occupation="Mechanic",   IsActive=true, CreatedDate=DateTime.UtcNow, LastVisitDate=DateTime.UtcNow.AddDays(-18) },
            };

            foreach (var p in patients)
            {
                p.UserId              = null;
                p.MedicalHistory      = string.Empty;
                p.Allergies           = string.Empty;
                p.GuardianName        = string.Empty;
                p.GuardianPhone       = string.Empty;
                p.ProfileImagePath    = string.Empty;
            }

            await _context.Patients.AddRangeAsync(patients);
            await _context.SaveChangesAsync();
            _logger.LogInformation("Seeded {Count} demo patients", patients.Length);
        }

        // ── Appointments ─────────────────────────────────────────────────────────

        private async Task SeedAppointmentsAsync()
        {
            if (await _context.Appointments.AnyAsync()) return;

            var patients = await _context.Patients.OrderBy(p => p.Id).Take(15).ToListAsync();
            var doctors  = await _context.Doctors.OrderBy(d => d.Id).ToListAsync();

            if (!patients.Any() || !doctors.Any()) return;

            var now = DateTime.UtcNow;
            var appointments = new List<Appointment>();

            var slots = new[]
            {
                new TimeSpan(9, 0, 0), new TimeSpan(9, 30, 0), new TimeSpan(10, 0, 0),
                new TimeSpan(10, 30, 0), new TimeSpan(11, 0, 0), new TimeSpan(14, 0, 0),
                new TimeSpan(14, 30, 0), new TimeSpan(15, 0, 0),
            };

            var statuses = new[] { "Completed", "Confirmed", "Scheduled", "Completed", "No Show" };
            var types    = new[] { "OPD", "Consultation", "Follow-Up" };
            var symptoms = new[] {
                "Fever and body ache", "Chest pain on exertion", "Knee pain while walking",
                "Recurring cough and cold", "Lower abdominal pain", "Ear discharge",
                "High blood pressure", "Back pain", "Dizziness and headache", "Skin rash"
            };

            var rand = new Random(42);

            for (var i = 0; i < patients.Count; i++)
            {
                var patient    = patients[i];
                var doctor     = doctors[i % doctors.Count];
                var daysOffset = -(i % 10 + 1);                // past appointments
                var date       = now.Date.AddDays(daysOffset);
                var status     = i < 10 ? "Completed" : (i < 13 ? "Confirmed" : "Scheduled");

                appointments.Add(new Appointment
                {
                    PatientId       = patient.Id,
                    DoctorId        = doctor.Id,
                    AppointmentDate = date,
                    AppointmentTime = slots[i % slots.Length],
                    Status          = status,
                    AppointmentType = types[i % types.Length],
                    Priority        = "Normal",
                    Symptoms        = symptoms[i % symptoms.Length],
                    Notes           = string.Empty,
                    CreatedDate     = now.AddDays(daysOffset - 1),
                    CreatedBy       = "System",
                    UpdatedBy       = string.Empty,
                });
            }

            // Add a few upcoming appointments
            for (var i = 0; i < 5; i++)
            {
                appointments.Add(new Appointment
                {
                    PatientId       = patients[i].Id,
                    DoctorId        = doctors[(i + 2) % doctors.Count].Id,
                    AppointmentDate = now.Date.AddDays(i + 1),
                    AppointmentTime = slots[(i + 2) % slots.Length],
                    Status          = "Scheduled",
                    AppointmentType = "OPD",
                    Priority        = "Normal",
                    Symptoms        = symptoms[(i + 4) % symptoms.Length],
                    Notes           = string.Empty,
                    CreatedDate     = now,
                    CreatedBy       = "System",
                    UpdatedBy       = string.Empty,
                });
            }

            await _context.Appointments.AddRangeAsync(appointments);
            await _context.SaveChangesAsync();
            _logger.LogInformation("Seeded {Count} appointments", appointments.Count);
        }

        // ── OPD Visits ───────────────────────────────────────────────────────────

        private async Task SeedOpdVisitsAsync()
        {
            if (await _context.OPDVisits.AnyAsync()) return;

            var patients = await _context.Patients.OrderBy(p => p.Id).Take(10).ToListAsync();
            var doctors  = await _context.Doctors.OrderBy(d => d.Id).ToListAsync();

            if (!patients.Any() || !doctors.Any()) return;

            var diagnoses = new[]
            {
                "Viral fever — symptomatic treatment prescribed",
                "Hypertension — medication adjusted",
                "Type 2 Diabetes Mellitus — glucose management reviewed",
                "Acute bronchitis — antibiotics prescribed",
                "Musculoskeletal lower back pain — physiotherapy recommended",
                "Allergic rhinitis — antihistamines prescribed",
                "Gastritis — PPI therapy initiated",
                "Anaemia — iron supplementation prescribed",
                "Upper respiratory tract infection — supportive care",
                "Osteoarthritis right knee — analgesics and physiotherapy",
            };

            var visits = new List<OPDVisit>();
            var now    = DateTime.UtcNow;

            for (var i = 0; i < patients.Count; i++)
            {
                visits.Add(new OPDVisit
                {
                    PatientId       = patients[i].Id,
                    DoctorId        = doctors[i % doctors.Count].Id,
                    VisitDate       = now.Date.AddDays(-(i + 1)),
                    Symptoms        = "See diagnosis",
                    Diagnosis       = diagnoses[i],
                    Treatment       = "As per diagnosis",
                    Prescription    = string.Empty,
                    Notes           = string.Empty,
                    ConsultationFee = 200 + (i % 5) * 50,
                    PaymentStatus   = i < 8 ? "Paid" : "Pending",
                    CreatedDate     = now.AddDays(-(i + 1)),
                    CreatedBy       = "System",
                });
            }

            await _context.OPDVisits.AddRangeAsync(visits);
            await _context.SaveChangesAsync();
            _logger.LogInformation("Seeded {Count} OPD visits", visits.Count);
        }

        // ── IPD Admissions ───────────────────────────────────────────────────────

        private async Task SeedIpdAdmissionsAsync()
        {
            if (await _context.IPDAdmissions.AnyAsync()) return;

            var patients = await _context.Patients.OrderBy(p => p.Id).Skip(5).Take(5).ToListAsync();
            var doctors  = await _context.Doctors.OrderBy(d => d.Id).ToListAsync();
            var beds     = await _context.Beds.Where(b => b.Status == "Available" && b.BedType == "General").Take(5).ToListAsync();

            if (!patients.Any() || !doctors.Any()) return;

            var admissionTypes = new[] { "Emergency", "Elective", "Referral" };
            var now = DateTime.UtcNow;

            var admissions = new List<IPDAdmission>();

            for (var i = 0; i < Math.Min(patients.Count, 5); i++)
            {
                var discharged   = i < 3;
                var admDate      = now.AddDays(-(10 - i * 2));
                var dischargeDate= discharged ? (DateTime?)admDate.AddDays(3 + i) : null;
                var bed          = beds.Count > i ? beds[i] : null;

                admissions.Add(new IPDAdmission
                {
                    PatientId      = patients[i].Id,
                    DoctorId       = doctors[i % doctors.Count].Id,
                    BedId          = bed?.Id,
                    AdmissionDate  = admDate,
                    DischargeDate  = dischargeDate,
                    AdmissionType  = admissionTypes[i % admissionTypes.Length],
                    Diagnosis      = "Acute condition requiring inpatient monitoring",
                    Treatment      = "IV fluids, monitoring, specialist review",
                    Notes          = string.Empty,
                    Status         = discharged ? "Discharged" : "Admitted",
                    DailyCharges   = bed?.DailyCharges ?? 500,
                    CreatedDate    = admDate,
                    CreatedBy      = "System",
                });

                // Mark bed as occupied for active admissions
                if (!discharged && bed != null)
                {
                    bed.Status    = "Occupied";
                    bed.PatientId = patients[i].Id;
                    bed.LastUpdated = now;
                }
            }

            await _context.IPDAdmissions.AddRangeAsync(admissions);
            await _context.SaveChangesAsync();
            _logger.LogInformation("Seeded {Count} IPD admissions", admissions.Count);
        }

        // ── Bills ────────────────────────────────────────────────────────────────

        private async Task SeedBillsAsync()
        {
            if (await _context.Bills.AnyAsync()) return;

            var patients = await _context.Patients.OrderBy(p => p.Id).Take(12).ToListAsync();
            if (!patients.Any()) return;

            var now  = DateTime.UtcNow;
            var bills = new List<Bill>();

            var serviceItems = new[]
            {
                ("Consultation Fee",     "Service",   200m),
                ("Blood Test (CBC)",     "Lab",       350m),
                ("X-Ray Chest",          "Radiology", 500m),
                ("ECG",                  "Radiology", 300m),
                ("Urine Analysis",       "Lab",       150m),
                ("Physiotherapy Session","Service",   400m),
                ("Dressing Change",      "Service",   120m),
                ("IV Cannulation",       "Service",   80m),
            };

            for (var i = 0; i < patients.Count; i++)
            {
                var billDate = now.AddDays(-(i + 1));
                var isPaid   = i < 8;
                var items    = new List<BillItem>();

                // 1-3 items per bill
                for (var j = 0; j <= i % 3; j++)
                {
                    var (name, type, price) = serviceItems[(i + j) % serviceItems.Length];
                    items.Add(new BillItem
                    {
                        ItemName    = name,
                        ItemType    = type,
                        Quantity    = 1,
                        UnitPrice   = price,
                        TotalPrice  = price,
                        Description = string.Empty,
                        CreatedDate = billDate,
                    });
                }

                var total   = items.Sum(x => x.TotalPrice);
                var paid    = isPaid ? total : (i == 8 ? Math.Round(total / 2, 2) : 0m);
                var pending = total - paid;
                var status  = isPaid ? "Paid" : (paid > 0 ? "Partially Paid" : "Unpaid");

                var bill = new Bill
                {
                    BillNumber  = $"BILL-{now.Year}-{(i + 1):D4}",
                    PatientId   = patients[i].Id,
                    BillDate    = billDate,
                    DueDate     = billDate.AddDays(30),
                    TotalAmount = total,
                    PaidAmount  = paid,
                    PendingAmount = pending,
                    Status      = status,
                    BillType    = "OPD",
                    Notes       = string.Empty,
                    CreatedDate = billDate,
                    CreatedBy   = "System",
                    BillItems   = items,
                };

                if (isPaid)
                {
                    bill.Payments.Add(new Payment
                    {
                        PaymentMethod = i % 3 == 0 ? "Cash" : (i % 3 == 1 ? "Card" : "Online"),
                        Amount        = total,
                        TransactionId = $"TXN{now.Year}{i:D6}",
                        PaymentGateway= string.Empty,
                        Status        = "Completed",
                        Notes         = string.Empty,
                        PaymentDate   = billDate.AddHours(1),
                        ProcessedBy   = "System",
                    });
                }

                bills.Add(bill);
            }

            await _context.Bills.AddRangeAsync(bills);
            await _context.SaveChangesAsync();
            _logger.LogInformation("Seeded {Count} bills", bills.Count);
        }
    }
}
